# Generated by Django 4.1 on 2023-03-31 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import pickaroom.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('features', models.TextField(blank=True, null=True)),
                ('structure_map_link', models.CharField(blank=True, max_length=100, null=True)),
                ('post_code', models.CharField(max_length=10)),
                ('star_rating', models.PositiveSmallIntegerField()),
                ('address', models.TextField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'post_code')},
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.PositiveSmallIntegerField()),
                ('room_no', models.CharField(max_length=10, verbose_name='room number')),
                ('row', models.PositiveSmallIntegerField()),
                ('column', models.PositiveSmallIntegerField()),
                ('size', models.PositiveSmallIntegerField()),
                ('cost', models.FloatField(default=0)),
                ('hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pickaroom.hotel')),
                ('room_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pickaroom.roomtype')),
            ],
            options={
                'ordering': ['hotel', 'floor', 'row', 'column'],
                'unique_together': {('hotel', 'room_type', 'room_no', 'row', 'column', 'floor')},
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_no', models.CharField(default=pickaroom.utils.generate_reference_no, max_length=20, unique=True)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('duration', models.PositiveSmallIntegerField(default=1)),
                ('num_adults', models.PositiveSmallIntegerField(default=1)),
                ('num_children', models.PositiveSmallIntegerField(default=0)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rooms', models.ManyToManyField(to='pickaroom.room')),
            ],
            options={
                'ordering': ['-start_date', '-duration'],
            },
        ),
    ]
