# Generated by Django 4.1 on 2023-03-31 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pickaroom', '0002_booking_hotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='hotel',
        ),
    ]
